AWS CIS v3.0.0 - Section 3 - Logging
turbot/guardrails-samples pull request #706
Opened 2024-05-08 11:00 UTC by vkumbha

2024-05-08 13:45 UTC, dboeke commented
@vkumbha per the standards doc:  https://turbothq.slack.com/archives/C06DF1TE16D/p1715141992661679?thread_ts=1715088393.985959&cid=C06DF1TE16D   
```
multi-line strings should use the [indented heredoc](https://developer.hashicorp.com/terraform/language/expressions/strings#indented-heredocs) `<<-EOT` style.
```

2024-05-08 13:46 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s3_logging/bucket.tf
> +  template_input = <<EOT
let's use `<<-EOT` for all multiline strings and not `EOV` etc..

2024-05-08 13:48 UTC, dboeke requested changes

2024-05-08 13:48 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s3_logging/common.tf
> +resource "turbot_smart_folder" "aws_cis_v300_s3_logging" {
add `# Smart Folder` comment

2024-05-08 13:48 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s3_logging/main.tf
> +provider "turbot" {
get rid of the profile variable, per the doc and the example.

2024-05-08 13:48 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s3_logging/trail.tf
> +  note     = <<EON
note fields don't support Multi-line strings.  keep the note simple and add comments above the policy setting if needed.

2024-05-10 06:38 UTC, vkumbha commented on cis_enforcements/aws/cis_v300_s3_logging/main.tf
> +variable "encryption_key" {
Log file SSE-KMS encryption is set to Enabled by default. CIS 3.05 is looking for CMK located in the same region as the S3 bucket with necessary a KMS Key policies.

2024-05-14 18:06 UTC, SumitPopat approved these changes

2024-05-14 18:07 UTC, merged