Add AWS > CIS3.0 > Section 5 enforcements. Closes #708
turbot/guardrails-samples pull request #709
Opened 2024-05-08 15:56 UTC by Subhajit97

2024-05-08 17:32 UTC, SumitPopat requested changes

2024-05-09 12:26 UTC, SumitPopat approved these changes

2024-05-09 12:44 UTC, dboeke requested changes

2024-05-09 12:44 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s5_networking/ec2_account_attributes.tf
> +  note     = "AWS CIS v3.0.0 - Controls: 5.6"
Note should be above the value.

2024-05-09 12:44 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s5_networking/network_acl.tf
> +  note     = "AWS CIS v3.0.0 - Controls: 5.1"
order of the attributes should be:

1. resource
2. type
3. note
4. value
5. template input
6. template

2024-05-09 12:44 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s5_networking/security_group.tf
> +      value: constant(value: "REJECT *")
no reason to do this as a constant.  only if we have separate enforce/check options in the policy setting.  in this case the calc policy will be the same regardless of check/enforce.

2024-05-09 12:44 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s5_networking/security_group.tf
> +      value: constant(value: "REJECT *")
same comment here about no need for this constant value, as it doesn't change.

2024-05-09 14:13 UTC, dboeke approved these changes

2024-05-09 14:13 UTC, merged