CIS 1.17
turbot/guardrails-samples pull request #710
Opened 2024-05-08 19:34 UTC by Joeturbot

CIS 1.17
- Added AWS > IAM > Stack
- Added AWS > IAM > Stack > Source
- Added AWS > IAM > Stack > Terraform Version

Checklist:
 3. Policy TF files: Checked.  All related policies are in the support_role.tf file.
 4. Policy Comments: Checked. 
    Smart Folder:  Checked.  matches the smart folder ID for all other policy settings in the IAM section.
    Terraform fmt: Checked.
    Order of Fields: Checked.  They are in the proper order.
    Notes: All policy settings in support_role.tf file are "AWS CIS v3.0.0 - Controls:  1.17"
    Multi-line strings:  Correctly use TF heredoc format.
 5. Enforcement:  All applicable policies are set to `Check`
   Commented Enforcement:  Checked.  All Enforcement values are commented out. 
   Comment Whitespace:  All commented enforcement values are prefixed with `  # value` as required.
 6. Enforcement options for calc policy:  No applicable to IAM > Stack.
 7.  Variables:  No variables used in these policy settings.   
    
    
 `terraform fmt` applied to all policy files in this directory.  Committing the updates.

2024-05-09 12:44 UTC, dboeke requested changes
Please make the requested changes.

2024-05-09 12:44 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s1_iam/support_role.tf
> +  template_input = <<EOT
Please use indented herdoc, per the spec.

2024-05-09 12:44 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s1_iam/support_role.tf
> +  template       = <<EOT
indented herdoc

2024-05-09 14:17 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s1_iam/support_role.tf
> +  EOT
Please checkout the link in the design spec about using **_Indented_ HEREDOC** format.

should be <<-EOT  and the lines should be indented 2 spaces more.

2024-05-09 14:18 UTC, dboeke commented on cis_enforcements/aws/cis_v300_s1_iam/support_role.tf
> +  EOT
same here

2024-05-14 18:09 UTC, SumitPopat approved these changes

2024-05-14 18:09 UTC, merged