Add policy pack - Check Azure VNets have flow log enabled. Closes #893
turbot/guardrails-samples pull request #894
Opened 2024-12-23 09:47 UTC by vkumbha

## Policy Pack
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/112dbbde-ac28-45a9-bc28-8e1e7811d84c" />

### Flow Log is not configured
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/ba9832eb-7f10-4298-9bb8-c0ceca60f869" />

### Flow Log is configured but not enabled
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/0fa31fcd-9952-4688-807e-cc6529f5c642" />

### Flow Log is configured but the resource is not found in CMDB to determine if it is enabled/disabled
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/8bc23207-f238-48d5-842d-a6a9b996b459" />

### Flow Log is configured and enabled
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/f726e4a6-0404-4bab-8b02-dd120c9247a8" />

2025-01-18 15:55 UTC, SumitPopat requested changes

2025-01-18 15:55 UTC, SumitPopat commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/policies.tf
> +  value    = "Check: Approved"
Do we only want to add the `Check` option?
In general, we include the `Enforce` option as well if the policy supports it.

2025-01-18 15:55 UTC, SumitPopat commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/main.tf
> +  akas        = ["azure_network_check_virtual_networks_have_flowlog_enabled"]
I think the aka would be `azure_network_enforce_virtual_networks_have_flowlog_enabled` if we include the `Enforce` option too?

2025-01-18 15:55 UTC, SumitPopat commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/policies.tf
> +          }
```suggestion
          name: get(path:"name")
          flowLogs: get(path:"flowLogs")
        }
      }
    - |
      {
        resource {
          name: get(path:"name")
          flowLogs: get(path:"flowLogs")
        }
        resources(filter:"resourceTypeId:tmod:@turbot/azure-networkwatcher#/resource/types/flowLog $.id:'{{ $.resource.flowLogs[0].id }}' resourceTypeLevel:self"){
          items {
            enabled:get(path:"enabled")
            id:get(path:"id")
            name:get(path:"name")
          }
```

2025-01-18 15:55 UTC, SumitPopat commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/policies.tf
> +
Please use the existing format for setting approved > custom policies. For reference please check: https://github.com/turbot/guardrails-samples/blob/main/policy_packs/aws/ec2/enforce_instances_use_amis_with_approved_tags/policies.tf#L13

2025-01-18 15:55 UTC, SumitPopat commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/README.md
> +- Validate that flow logging status is enabled
```suggestion
This [policy pack](https://turbot.com/guardrails/docs/concepts/policy-packs) can help you configure the following settings for virtual networks:

- Check if flow logs are configured and enabled
- Delete unapproved virtual networks if flow logging is not enabled
```

2025-01-18 15:55 UTC, SumitPopat commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/README.md
> +For more information, please see [Policy Packs](https://turbot.com/guardrails/docs/concepts/policy-packs).
Please add the `Enable Enforcement` block if the `Enforce` option is added to the Policy Pack.

2025-01-22 07:08 UTC, vkumbha commented on policy_packs/azure/network/check_virtual_networks_have_flowlogs_enabled/policies.tf
> +  value    = "Check: Approved"
@sumit I believe that if a Virtual Network does not have Flow Logs enabled, the goal should be to enforce the creation of Flow Logs rather than deleting the VNet. However, since the Azure Flow Log stack (similar to the [AWS > VPC > VPC > Flow Logging](https://hub.guardrails.turbot.com/mods/aws/controls/aws-vpc-core/vpcFlowloggingStack)) is not currently available, we decided to proceed with a Check mode approach in this case.

2025-05-20 23:35 UTC, closed without merging